updates:
  - directory: "/"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
  - directory: "/src/ScarletRadioControl.Web.Frontend/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
version: 2
